### ISSUE TITLE
Why the "GenerateThumbnails" is before "PublishArchive"/"PublishArchives"?

### ISSUE THREAD

**Issue by thang1160** [rs1703/koushoku#10]
I was wondering why you place it like that. Because whenever I upload, I run 
`util --index --publish-all --generate-thumbnails --generate-cache`
Which only takes 1 command beside restart the backend service

**Comment by rs1703** [comment]
Now that I look at it again, you have a point. It's probably my mistake since I don't use those commands anymore, and I don't know why the command `generate-cache` even exist but it's really unnecessary. I'll clean up the spaghetti code and push some commits later.

**Comment by thang1160** [comment]
So which command do you use for uploading?

**Comment by rs1703** [comment]
> So which command do you use for uploading?

I used to use the `--index` command when I first started, but now I'm using the `--add=/path/to/archive` command since it's much faster. You can keep using the `--index` command if you are not doing some kind of filtering, otherwise it would re-add the removed archives. Or you could just move the unneeded archives to a different folder to prevent it from being re-indexed.

My routine is just:
```bash
./util --add=/path/to/archive1
./util --add=/path/to/archive2
./util --publish-all
./util --scrape-id <id-of-archive1> --fpath=/hentai/path-to-f-1
./util --scrape-id <id-of-archive2> --fpath=/hentai/path-to-f-2
./util --import
```
which as you can tell, very not efficient.

**Comment by rs1703** [comment]
That should do it, I guess
