### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by Ramzh** [rs1703/koushoku#5]
Hi

Thanks for the awesome project, I am planning to host this myself once I am done with my server build.

I am a curious mind and totally not a webdev expert and hope you could share/explain how you achieve almost simultaneous sync with the [redacted] site. 

Would be probably better in DMs

Let me know

**Comment by rs1703** [comment]
I wouldn't recommend this project if your intention is to use it as a personal library since everything has to be managed from the command line interface, and honestly it's a spaghetti since I made it within a week and don't have any time to polish it, but if your intention is to redistribute it to the web, then I'll gladly help.

You can contact me through one of these, but don't expect fast response time:
CuteAndFunny # 8182
koushoku-dev at protonmail.com
